# Generated by Django 4.1.3 on 2022-12-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=255)),
                ('desc', models.TextField(default='description')),
            ],
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(help_text='name', max_length=255),
        ),
    ]
